# Final Project: EPA Toxic Spill Analysis

### Statement of Need

The Environmental Protection Agency has been keeping track of the release of toxic chemicals into the environment since 1987. 
We know that systemic racism, including redlining and white flight, has meant that Black and brown folks are much more likely to be affected by things like worse air quality, pipelines being built across their lands, and more.  Large power plants and other polluters are also much more likely to be built in and around Black neighborhoods (creating things like cancer alley in Louisiana). 
The EPA would like to work to a) find the extent of these issues as they relate to toxic spills in order to find potential interventions or policy solutions to these issues, and b) help predict where these spills might happen again to prevent it. 
This final project will deliver an interactive dashboard using ESRI Insights that showcases: the extent to which toxic spills affect low income communities of color over others, and where we can predict spills to happen again. 

### Phase 1: Exploratory Data Analysis



### Phase 2: Demographics Analysis


### Phase 3: Prediction

### Conclusion


